export const GEMINI_CLASSIFICATION_MODEL = 'gemini-3.5-flash-lite' as const;
export const GEMINI_CLASSIFICATION_DEADLINE_MS = 10_000;
export const GEMINI_CLASSIFICATION_MAX_ATTEMPTS = 2;
export const GEMINI_CLASSIFICATION_MIN_RETRY_BUDGET_MS = 1_000;
